- README.md
> README.md updated (minor updates)

- README.md
Tools intro section had some accidentally a word.
> README: fixup tools grammar

- README.md
> ServiceDesk email removed and other minor cleanup

- README.md
> Credentials sharing tip added

- README.md
> Cloud computing and similar services explained

- README.md
Update the services for projects with current information.
> Update services for projects

- README.md
Signed-off-by: Ken Sipe <kensipe@gmail.com>
> Correct Zapier URL

- README.md
> AWS budget estimate added

- README.md
> Docker Hub waived limits policy added

- README.md
cc: @caniszczyk @zacharysarah @amye
> Add information about technical writing services

- README.md
> CNCF ServiceDesk policy for K8s referenced

- README.md
Hi there 👋 . After chatting with @caniszczyk today, this was suggested as Scarf intends to be an analytics resource for all CNCF projects. Happy to make any needed modifications, move to a better section, etc, just let me know.
Also fixed two typos found along the way.
> Add Scarf to tools section

- README.md
Signed-off-by: Justin Cappos <justincappos@gmail.com>
> Fix to reflect the new TAG-Security name

- README.md
Signed-off-by: Tiger Kaovilai <passawit.kaovilai@gmail.com>
> use archive.org bloomberg rollout

- README.md
Signed-off-by: lloydchang <lloydchang@gmail.com>
> docs(README.md): fix typos, add trailing newline

- README.md
ToC added + minor formatting tweaks
> Table of contents added

- README.md
As Amye would say, "what it says on the tin."
> Merged Ihor's pull request, linted Markdown, fixed grammar, fixed links

- README.md
Adds _my_ descriptions of the CLO suite of apps and Git Vote.
Deliberately looking for considered, reviews for tone, style, and messaging.
> adds CLO apps and GitVote

- README.md
Noticed this when looking at project benefits. 👍
> Sandbox projects do not get maintainer sessions

- README.md
* Scarf is legally approved by LF
* Dosu is early access and YMMV
> Add getting started link for Scarf and early access for Dosu.
